import nodemailer from 'nodemailer';

// You will need to add these to your .env.local file:
// EMAIL_HOST (e.g., smtp.gmail.com)
// EMAIL_PORT (e.g., 587)
// EMAIL_USER (e.g., your-email@gmail.com)
// EMAIL_PASS (App Password, NOT account password)

const transporter = nodemailer.createTransport({
    host: process.env.EMAIL_HOST || 'smtp.gmail.com',
    port: parseInt(process.env.EMAIL_PORT || '587'),
    secure: process.env.EMAIL_SECURE === 'true', // true for 465, false for other ports
    auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
    },
});

export interface OrderDetails {
    orderId: string;
    customerEmail: string;
    customerPhone: string;
    customerName?: string;
    items: {
        name: string;
        quantity: number;
        price: number;
        size: string;
    }[];
    total: number;
}

export async function sendQuoteEmail(order: OrderDetails) {
    // If credentials aren't set, log and return early in development
    if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
        console.warn('Email credentials not configured. Skipping email send for order:', order.orderId);
        return false;
    }

    const itemsListHtml = order.items.map(item => `
        <tr>
            <td style="padding: 8px; border-bottom: 1px solid #ddd;">${item.name} (${item.size})</td>
            <td style="padding: 8px; border-bottom: 1px solid #ddd; text-align: center;">${item.quantity}</td>
            <td style="padding: 8px; border-bottom: 1px solid #ddd; text-align: right;">₹${item.price.toFixed(2)}</td>
            <td style="padding: 8px; border-bottom: 1px solid #ddd; text-align: right;">₹${(item.price * item.quantity).toFixed(2)}</td>
        </tr>
    `).join('');

    const html = `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2 style="color: #059669;">New Quote Request</h2>
            <p><strong>Order ID:</strong> ${order.orderId}</p>
            <p><strong>Customer Email:</strong> ${order.customerEmail}</p>
            <p><strong>Customer Phone:</strong> ${order.customerPhone}</p>
            ${order.customerName ? `<p><strong>Customer Name:</strong> ${order.customerName}</p>` : ''}
            
            <h3 style="margin-top: 20px;">Requested Items</h3>
            <table style="width: 100%; border-collapse: collapse; margin-top: 10px;">
                <thead>
                    <tr style="background-color: #f3f4f6;">
                        <th style="padding: 8px; text-align: left; border-bottom: 2px solid #ddd;">Item</th>
                        <th style="padding: 8px; text-align: center; border-bottom: 2px solid #ddd;">Qty</th>
                        <th style="padding: 8px; text-align: right; border-bottom: 2px solid #ddd;">Price</th>
                        <th style="padding: 8px; text-align: right; border-bottom: 2px solid #ddd;">Total</th>
                    </tr>
                </thead>
                <tbody>
                    ${itemsListHtml}
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="3" style="padding: 12px 8px; text-align: right; font-weight: bold;">Grand Total:</td>
                        <td style="padding: 12px 8px; text-align: right; font-weight: bold;">₹${order.total.toFixed(2)}</td>
                    </tr>
                </tfoot>
            </table>
            <p style="margin-top: 20px; color: #666; font-size: 0.9em;">
                This quote request was automatically generated by the Govinda's Horticulture Nursery Chat Assistant.
            </p>
        </div>
    `;

    try {
        const info = await transporter.sendMail({
            from: `"Govinda's Horticulture Nursery" <${process.env.EMAIL_USER}>`,
            to: 'ramprasadre56@gmail.com',
            subject: `New Quote Request - ${order.orderId}`,
            html: html,
        });
        
        console.log('Quote email sent: %s', info.messageId);
        return true;
    } catch (error) {
        console.error('Error sending quote email:', error);
        return false;
    }
}
